"""
VOID Tools — Dox Creator
Accepts victim profile fields via query params, returns a structured JSON dox report.
For authorized research, documentation, and CTF use only.
GET /api/dox?name=John&surname=Doe&age=25&...&lang=en
"""
from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import json
from datetime import datetime, timezone

LABELS = {
    "en":{
        "tool":"Dox Creator",
        "note":"For authorized research and documentation only. Misuse is illegal.",
        "generated":"Report generated",
    },
    "fr":{
        "tool":"Créateur de Dox",
        "note":"Pour la recherche autorisée et la documentation uniquement. Toute utilisation abusive est illégale.",
        "generated":"Rapport généré",
    },
}

FIELDS = [
    # Personal
    ("name","Name"),("surname","Surname"),("age","Age"),("dob","Date of Birth"),
    ("country","Country"),("city","City"),("address","Address"),
    ("situation","School/Job Situation"),("other","Other Info"),
    # Online
    ("nickname","Nickname"),("email","Email"),("phone","Phone"),
    ("youtube","YouTube"),("instagram","Instagram"),("discord","Discord"),
    ("twitter","Twitter"),("facebook","Facebook"),
    # Father
    ("father_name","Father Name"),("father_surname","Father Surname"),
    ("father_age","Father Age"),("father_location","Father Location"),
    ("father_job","Father Job"),("father_info","Father Other Info"),
    # Mother
    ("mother_name","Mother Name"),("mother_surname","Mother Surname"),
    ("mother_age","Mother Age"),("mother_location","Mother Location"),
    ("mother_job","Mother Job"),("mother_interests","Mother Interests"),
    ("mother_info","Mother Other Info"),
    # PC
    ("pc_name","PC Name"),("pc_brand","PC Brand"),("pc_model","PC Model"),
    ("pc_os","PC OS"),("mac_address","MAC Address"),("ip_address","IP Address"),
    ("pc_other","PC Other Info"),
]

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        parsed = urlparse(self.path); params = parse_qs(parsed.query)
        lang = params.get("lang",["en"])[0].lower()
        if lang not in LABELS: lang = "en"
        L = LABELS[lang]

        def send(status, payload):
            body = json.dumps(payload, ensure_ascii=False, indent=2).encode()
            self.send_response(status)
            self.send_header("Content-Type","application/json; charset=utf-8")
            self.send_header("Access-Control-Allow-Origin","*")
            self.send_header("Content-Length",str(len(body)))
            self.end_headers(); self.wfile.write(body)

        data = {}
        for key, label in FIELDS:
            val = params.get(key,[""])[0].strip()
            data[key] = {"label":label,"value":val if val else "N/A"}

        dox_name = params.get("dox_name",["unnamed"])[0].strip() or "unnamed"
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        report_lines = [
            "╔══════════════════════════════════════════╗",
            f"║  VOID TOOLS — DOX REPORT                 ║",
            f"║  Name: {dox_name:<34}║",
            f"║  {ts:<42}║",
            "╚══════════════════════════════════════════╝",
            "",
            "── PERSONAL INFORMATION ──────────────────",
        ]
        personal_keys = ["name","surname","age","dob","country","city","address","situation","other"]
        for k in personal_keys:
            if k in data: report_lines.append(f"  {data[k]['label']:<22}: {data[k]['value']}")
        report_lines += ["","── ONLINE PRESENCE ───────────────────────"]
        online_keys = ["nickname","email","phone","youtube","instagram","discord","twitter","facebook"]
        for k in online_keys:
            if k in data: report_lines.append(f"  {data[k]['label']:<22}: {data[k]['value']}")
        report_lines += ["","── FATHER INFORMATION ────────────────────"]
        father_keys = ["father_name","father_surname","father_age","father_location","father_job","father_info"]
        for k in father_keys:
            if k in data: report_lines.append(f"  {data[k]['label']:<22}: {data[k]['value']}")
        report_lines += ["","── MOTHER INFORMATION ────────────────────"]
        mother_keys = ["mother_name","mother_surname","mother_age","mother_location","mother_job","mother_interests","mother_info"]
        for k in mother_keys:
            if k in data: report_lines.append(f"  {data[k]['label']:<22}: {data[k]['value']}")
        report_lines += ["","── PC INFORMATION ────────────────────────"]
        pc_keys = ["pc_name","pc_brand","pc_model","pc_os","mac_address","ip_address","pc_other"]
        for k in pc_keys:
            if k in data: report_lines.append(f"  {data[k]['label']:<22}: {data[k]['value']}")
        report_lines += ["","── Generated by VOID TOOLS ───────────────"]

        send(200,{
            "tool":L["tool"],"success":True,"lang":lang,
            "dox_name":dox_name,
            "generated_at":ts,
            "note":L["note"],
            "data":data,
            "report":"\n".join(report_lines),
        })

    def log_message(self, *args): pass
